// Generated by LiveScript 1.5.0
/**
 * @package CleverStyle Widgets
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  window.csw || (window.csw = {});
  csw.behaviors || (csw.behaviors = {});
  csw.functions || (csw.functions = {});
}).call(this);
