// Generated by LiveScript 1.5.0
/**
 * @package CleverStyle Widgets
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  csw.behaviors.button = {
    properties: {
      active: {
        notify: true,
        reflectToAttribute: true,
        type: Boolean
      },
      empty: {
        reflectToAttribute: true,
        type: Boolean
      },
      iconBefore: {
        type: String
      },
      iconAfter: {
        type: String
      },
      icon: {
        type: String
      },
      primary: {
        reflectToAttribute: true,
        type: Boolean
      }
    },
    ready: function(){
      var iconBefore;
      this.empty = !this.firstElementChild.childNodes.length;
      iconBefore = this.iconBefore || this.icon;
      if (iconBefore) {
        this.firstElementChild.insertAdjacentHTML('afterbegin', "<csw-icon icon=\"" + iconBefore + "\" mono></csw-icon> ");
      }
      if (this.iconAfter) {
        this.firstElementChild.insertAdjacentHTML('beforeend', " <csw-icon icon=\"" + this.iconAfter + "\" mono></csw-icon>");
      }
    }
  };
}).call(this);
