// Generated by LiveScript 1.5.0
/**
 * @package   CleverStyle Widgets
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license   0BSD
 */
(function(){
  csw.behaviors.ready = {
    _when_ready: function(action){
      var callback;
      if (window.WebComponents && window.WebComponents.ready) {
        setTimeout(action);
      } else {
        callback = function(){
          setTimeout(action);
          document.removeEventListener('WebComponentsReady', callback);
        };
        document.addEventListener('WebComponentsReady', callback);
      }
    }
  };
}).call(this);
