// Generated by LiveScript 1.5.0
/**
 * @package CleverStyle Widgets
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  csw.behaviors.cswModal = [
    csw.behaviors['this'], {
      properties: {
        asIs: {
          reflectToAttribute: true,
          type: Boolean
        },
        autoDestroy: Boolean,
        autoOpen: Boolean,
        manualClose: Boolean,
        opened: {
          observer: '_opened_changed',
          type: Boolean
        }
      },
      listeners: {
        transitionend: '_transitionend'
      },
      _esc_handler: function(e){
        if (e.keyCode === 27 && !this.manualClose) {
          this.close();
        }
      },
      ready: function(){
        this._esc_handler = this._esc_handler.bind(this);
      },
      attached: function(){
        var ref$;
        if (((ref$ = this.previousElementSibling) != null && ref$.matches('csw-button')) && !this.previousElementSibling.action) {
          this.previousElementSibling.action = 'open';
          this.previousElementSibling.bind = this;
        }
        if (this.autoOpen) {
          this.autoOpen = false;
          this.open();
        }
      },
      _transitionend: function(){
        var ref$;
        if (!this.opened && this.autoDestroy) {
          if ((ref$ = this.parentNode) != null) {
            ref$.removeChild(this);
          }
        }
      },
      _overlay_tap: function(){
        if (!this.manualClose) {
          this.close();
        }
      },
      _opened_changed: function(opened){
        var ref$, body, ref1$, this$ = this;
        if (opened === undefined) {
          return;
        }
        if (!((ref$ = this.parentNode) != null && ref$.matches('html'))) {
          document.documentElement.appendChild(this);
        }
        this.distributeContent(true);
        Polymer.dom.flush();
        body = document.body;
        body.modalOpened = body.modalOpened || 0;
        if (opened) {
          if ((ref1$ = document.querySelector('csw-tooltip')) != null) {
            ref1$.show = false;
          }
          document.addEventListener('keydown', this._esc_handler);
          if (this.content) {
            this.innerHTML = this.content;
            this.content = null;
          }
          ++body.modalOpened;
          this.fire('open');
          body.setAttribute('modal-opened', '');
          setTimeout(function(){
            this$.setAttribute('opened', '');
          }, 100);
        } else {
          document.removeEventListener('keydown', this._esc_handler);
          --body.modalOpened;
          this.fire('close');
          this.removeAttribute('opened');
          if (!body.modalOpened) {
            body.removeAttribute('modal-opened');
          }
        }
      },
      open: function(){
        if (!this.opened) {
          this.opened = true;
        }
        return this;
      },
      close: function(){
        if (this.opened) {
          this.opened = false;
        }
        return this;
      }
    }
  ];
}).call(this);
