// Generated by LiveScript 1.5.0
/**
 * @package CleverStyle Widgets
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  csw.behaviors.cswGroup = [{
    hostAttributes: {
      role: 'group'
    },
    properties: {
      vertical: {
        reflectToAttribute: true,
        type: Boolean
      }
    }
  }];
}).call(this);
