// Generated by LiveScript 1.5.0
/**
 * @package CleverStyle Widgets
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  Polymer({
    is: 'csw-label-switcher',
    behaviors: csw.behaviors.cswLabelSwitcher
  });
}).call(this);
